# -*- coding: utf-8 -*-
"""Medical Diagnosis of X-Ray .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156ppc9ctkR7GIIIhc0d5XUOh30BzAU9-

# **Installing Required Libraries**
"""

!pip install -q tensorflow transformers tf-explain grad-cam kaggle

"""# **Loading Libraries**"""

import os
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import cv2
import seaborn as sns

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16, ResNet50
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

"""# **Uploading and Downloading Kaggle Dataset**"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

with zipfile.ZipFile(
    "chest-xray-pneumonia.zip",
    'r'
) as zip_ref:

    zip_ref.extractall("/content")

train_dir = "/content/chest_xray/train"
test_dir = "/content/chest_xray/test"
val_dir = "/content/chest_xray/val"

"""# **Data Preprocessing**"""

IMG_SIZE = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(
    rescale=1./255
)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary'
)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='binary',
    shuffle=False
)

"""# Sample Images"""

images, labels = next(train_data)

plt.figure(figsize=(10,10))

for i in range(9):

    plt.subplot(3,3,i+1)
    plt.imshow(images[i])

    if labels[i] == 1:
        plt.title("PNEUMONIA")
    else:
        plt.title("NORMAL")

    plt.axis("off")

plt.show()

"""# **VGG16 Model**"""

base_model = VGG16(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

for layer in base_model.layers:
    layer.trainable = False

x = Flatten()(base_model.output)

x = Dense(256, activation='relu')(x)

x = Dropout(0.5)(x)

output = Dense(1, activation='sigmoid')(x)

vgg_model = Model(
    inputs=base_model.input,
    outputs=output
)

vgg_model.compile(
    optimizer=Adam(0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

"""# Training the Model"""

history_vgg = vgg_model.fit(
    train_data,
    validation_data=test_data,
    epochs=5
)

"""Acurracy Graph"""

plt.figure(figsize=(12,5))

plt.plot(history_vgg.history['accuracy'])
plt.plot(history_vgg.history['val_accuracy'])

plt.title("VGG16 Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.legend(['Train','Validation'])
plt.show()

"""# Evaluating the Model"""

loss, accuracy = vgg_model.evaluate(test_data)
print("Test Accuracy:", accuracy)

predictions = vgg_model.predict(test_data)
predictions = (predictions > 0.5).astype(int)

cm = confusion_matrix(
    test_data.classes,
    predictions
)

plt.figure(figsize=(6,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['NORMAL','PNEUMONIA'],
    yticklabels=['NORMAL','PNEUMONIA']
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

print(classification_report(
    test_data.classes,
    predictions,
    target_names=['NORMAL','PNEUMONIA']
))

"""# ResNet50 Model"""

base_model_resnet = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

for layer in base_model_resnet.layers:
    layer.trainable = False

x = GlobalAveragePooling2D()(
    base_model_resnet.output
)

x = Dense(256, activation='relu')(x)

x = Dropout(0.5)(x)

output = Dense(1, activation='sigmoid')(x)

resnet_model = Model(
    inputs=base_model_resnet.input,
    outputs=output
)

resnet_model.compile(
    optimizer=Adam(0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

"""# Training the Model"""

history_resnet = resnet_model.fit(
    train_data,
    validation_data=test_data,
    epochs=5
)

from google.colab import files

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

img = tf.keras.preprocessing.image.load_img(
    image_path,
    target_size=(224,224)
)

img_array = tf.keras.preprocessing.image.img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)

img_array = img_array / 255.0

prediction = vgg_model.predict(img_array)

if prediction[0][0] > 0.5:
    print("PNEUMONIA DETECTED")
else:
    print("NORMAL")

"""# Grad-CAM Visualization"""

last_conv_layer_name = "block5_conv3"

grad_model = tf.keras.models.Model(
    [vgg_model.inputs],
    [
        vgg_model.get_layer(last_conv_layer_name).output,
        vgg_model.output
    ]
)

with tf.GradientTape() as tape:

    conv_outputs, predictions = grad_model(img_array)

    loss = predictions[:, 0]

grads = tape.gradient(loss, conv_outputs)

pooled_grads = tf.reduce_mean(
    grads,
    axis=(0,1,2)
)

heatmap = tf.reduce_mean(
    tf.multiply(
        pooled_grads,
        conv_outputs
    ),
    axis=-1
)

heatmap = heatmap.numpy()[0]
heatmap = np.maximum(heatmap, 0)
heatmap /= np.max(heatmap)

img = cv2.imread(image_path)
img = cv2.resize(img, (224,224))

heatmap = cv2.resize(heatmap, (224,224))
heatmap = np.uint8(255 * heatmap)
heatmap = cv2.applyColorMap(
    heatmap,
    cv2.COLORMAP_JET
)

superimposed_img = heatmap * 0.4 + img

plt.figure(figsize=(8,8))

plt.imshow(
    cv2.cvtColor(
        np.uint8(superimposed_img),
        cv2.COLOR_BGR2RGB
    )
)

plt.title("Grad-CAM Visualization")

plt.axis("off")

plt.show()

"""| Color              | Meaning             |
| ------------------ | ------------------- |
| Red / Pink         | Very high attention |
| Yellow / Green     | Moderate attention  |
| Blue               | Low attention       |
| Transparent / Dark | Very low importance |

In the Grad-CAM Visualization above tells:
*   The model is focusing strongly on the central chest region
*   Bright red/pink regions indicate the model considers those areas important
*   The highlighted regions near the lungs and mediastinum contribute most to
prediction

# Another X-Ray Image Example
"""

from google.colab import files

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

img = tf.keras.preprocessing.image.load_img(
    image_path,
    target_size=(224,224)
)

img_array = tf.keras.preprocessing.image.img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)

img_array = img_array / 255.0

prediction = vgg_model.predict(img_array)

if prediction[0][0] > 0.5:
    print("PNEUMONIA DETECTED")
else:
    print("NORMAL")

last_conv_layer_name = "block5_conv3"

grad_model = tf.keras.models.Model(
    [vgg_model.inputs],
    [
        vgg_model.get_layer(last_conv_layer_name).output,
        vgg_model.output
    ]
)

with tf.GradientTape() as tape:

    conv_outputs, predictions = grad_model(img_array)

    loss = predictions[:, 0]

grads = tape.gradient(loss, conv_outputs)

pooled_grads = tf.reduce_mean(
    grads,
    axis=(0,1,2)
)

heatmap = tf.reduce_mean(
    tf.multiply(
        pooled_grads,
        conv_outputs
    ),
    axis=-1
)

heatmap = heatmap.numpy()[0]
heatmap = np.maximum(heatmap, 0)
heatmap /= np.max(heatmap)

img = cv2.imread(image_path)
img = cv2.resize(img, (224,224))

heatmap = cv2.resize(heatmap, (224,224))
heatmap = np.uint8(255 * heatmap)
heatmap = cv2.applyColorMap(
    heatmap,
    cv2.COLORMAP_JET
)

superimposed_img = heatmap * 0.4 + img

plt.figure(figsize=(8,8))

plt.imshow(
    cv2.cvtColor(
        np.uint8(superimposed_img),
        cv2.COLOR_BGR2RGB
    )
)

plt.title("Grad-CAM Visualization")

plt.axis("off")

plt.show()

"""| Color          | Meaning                 |
| -------------- | ----------------------- |
| Red / Pink     | Highest model attention |
| Yellow / Green | Medium importance       |
| Blue / Purple  | Lower importance        |

The heatmap indicates that the CNN model mainly concentrated on:

*   the central thoracic region
*   upper mediastinum area
*   portions of both lung fields
----
The highlighted warm colors (red/yellow/pink) represent regions that
contributed more strongly to the model’s classification decision.
"""